name: build games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - games/**
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - altv
          - samp
          - source
          - dayz
          
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./games/${{ matrix.game }}
          file: ./games/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            quintenqvd/pterodactyl_tini:games_${{ matrix.game }}
